import os
import re

cwd = r'c:\Users\GBASILAIA\claude\ai2026\lectures10'
file_path = os.path.join(cwd, 'v2-lecture-9-slides.html')

with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    "Customization = Efficiency × Quality × Consistency": "მორგება = ეფექტურობა × ხარისხი × სტაბილურობა",
    "Upload documents (PDF, DOCX, TXT, CSV) → GPT uses as reference": "ატვირთეთ ფაილები (PDF, DOCX, TXT, CSV) → GPT მათ გამოიყენებს როგორც საყრდენ ბაზას",
    "Web Search:Access to current information (Bing + web)": "ვებ-ძიება (Web Search): წვდომა უახლეს ინფორმაციაზე",
    "DALL-E 4:Image generation built-in": "DALL-E 4: გამოსახულების გენერაცია ჩაშენებული სახით",
    "Code Interpreter:Run Python code, data analysis, charts": "Code Interpreter: პითონის კოდის გაშვება, მონაცემთა ანალიზი და გრაფიკები",
    "Canvas:Collaborative document/code editing (new 2026)": "Canvas: ერთობლივი დოკუმენტების და კოდის რედაქტირება (ახალი 2026)",
    "Connect to external APIs/services (advanced)": "დაკავშირება გარე API-ებთან და სერვისებთან (გაფართოებული)",
    "Anyone with link:share link-ით": "Anyone with link: გაზიარებული ბმულით",
    "Simple GPT: 5-10 წუთი | Complex GPT with files: 30-60 წუთი": "მარტივი GPT: 5-10 წუთი | რთული GPT ფაილებით: 30-60 წუთი",
    "Instruction Template (Best Practices)": "ინსტრუქციის შაბლონი (საუკეთესო პრაქტიკა)",
    "Add Project Knowledge → Upload Files": "დაამატეთ საპროექტო ცოდნა (Project Knowledge) → ატვირთეთ ფაილები",
    "Requirements:Claude Pro ($20/month)": "მოთხოვნები: Claude Pro ($20/თვეში)",
    "💡 Pro Tip: Project Organization": "💡 პროფესიონალური რჩევა: პროექტის ორგანიზება",
    "Create separate chats for different aspects": "შექმენით ცალკეული ჩატები სხვადასხვა ასპექტისთვის",
    "Use descriptive chat names for easy navigation": "გამოიყენეთ აღწერილობითი სახელები მარტივი ნავიგაციისთვის",
    "Regularly review and update Custom Instructions as project evolves": "რეგულარულად განაახლეთ ინსტრუქციები პროექტის განვითარებასთან ერთად",
    "Description:რას აკეთებს Gem": "აღწერა (Description): რას აკეთებს Gem",
    "Use cases:Brand guidelines, style guides, product docs, templates": "გამოყენების სცენარები: ბრენდის გაიდლაინები, სტილის დოკუმენტები, შაბლონები",
    "Options:Share link / Email invitation": "პარამეტრები: ბმულის გაზიარება / ელ-ფოსტით მოწვევა",
    "Function:Marketing analytics and strategy": "ფუნქცია: მარკეტინგული ანალიტიკა და სტრატეგია",
    "Calculate customer acquisition cost (CAC)": "მომხმარებლის მოზიდვის ღირებულების (CAC) გამოთვლა",
    "Forecast future behavior from historical data": "მომავალი ქცევის პროგნოზირება ისტორიული მონაცემებიდან",
    "Campaign performance analysis": "კამპანიის ეფექტურობის ანალიზი",
    "Budget optimization recommendations": "ბიუჯეტის ოპტიმიზაციის რეკომენდაციები",
    "Function:Sales materials creation": "ფუნქცია: გაყიდვების მასალების შექმნა",
    "Create compelling pitch decks": "დამაჯერებელი საპრეზენტაციო მასალების შექმნა",
    "Generate value propositions": "ღირებულების შეთავაზებების (Value Proposition) გენერაცია",
    "Competitive positioning": "კონკურენტული პოზიციონირება",
    "Objection handling scripts": "კლიენტის უარყოფასთან გამკლავების სკრიპტები",
    "Function:Recruitment support": "ფუნქცია: რეკრუტინგის მხარდაჭერა",
    "Write consistent job descriptions": "ვაკანსიის თანმიმდევრული აღწერების წერა",
    "Generate interview questions": "გასაუბრების კითხვების გენერაცია",
    "Candidate evaluation frameworks": "კანდიდატის შეფასების ჩარჩოები",
    "Onboarding materials": "ახალი თანამშრომლის ადაპტაციის (Onboarding) მასალები",
    "Function:Customer communication": "ფუნქცია: მომხმარებელთან კომუნიკაცია",
    "Personalized email campaigns": "პერსონალიზებული ელ-ფოსტის კამპანიები",
    "Customer support responses": "მომხმარებელთა მხარდაჭერის პასუხები",
    "Follow-up sequences": "Follow-up შეტყობინებების მიმდევრობები",
    "Relationship nurturing messages": "ურთიერთობის განმტკიცების შეტყობინებები",
    "Function:Brand content writing": "ფუნქცია: ბრენდის კონტენტის წერა",
    "On-brand marketing copy": "ბრენდის სტილზე მორგებული სარეკლამო ტექსტი",
    "Social media posts": "სოციალური მედიის პოსტები",
    "Ad copy variations": "სარეკლამო ტექსტის ვარიაციები",
    "Landing page content": "სადესანტო გვერდის (Landing Page) კონტენტი",
    "Function:Customer feedback analysis": "ფუნქცია: მომხმარებელთა უკუკავშირის ანალიზი",
    "Analyze customer reviews": "მომხმარებელთა მიმოხილვების ანალიზი",
    "Identify sentiment trends": "განწყობის ტენდენციების გამოვლენა",
    "Extract actionable insights": "პრაქტიკული და ღირებული დასკვნების ამოღება",
    "Track brand perception": "ბრენდის აღქმის მონიტორინგი",
    "Creative ideation, problem-solving, innovation prompts": "კრეატიული იდეები, პრობლემის გადაჭრა, ინოვაციური პრომპტები",
    "Career roadmaps, skill development, job search support": "კარიერული გეგმები, უნარების განვითარება, სამსახურის ძიების მხარდაჭერა",
    "Grammar, style, clarity improvements for any writing": "გრამატიკის, სტილის და სიცხადის გაუმჯობესება ნებისმიერი ტექსტისთვის",
    "Debugging, code explanations, programming tutorials": "კოდის შეცდომების გასწორება, ახსნა და პროგრამირების გაკვეთილები",
    "Share Gem with entire marketing team": "გაუზიარეთ Gem მარკეტინგის მთელ გუნდს",
    "Scenario:ემზადებით job interview-სთვის": "სცენარი: ემზადებით გასაუბრებისთვის",
    "Result:Personalized interview prep based on YOUR real experience!": "შედეგი: პერსონალიზებული მომზადება გასაუბრებისთვის თქვენს რეალურ გამოცდილებაზე დაყრდნობით!",
    "Full-length SEO blog posts in minutes instead of hours!": "სრულყოფილი SEO ბლოგ-პოსტები წუთებში, საათების ნაცვლად!",
    "Georgian business etiquette": "ქართული ბიზნეს ეტიკეტი",
    "French-style recipes + cooking instructions + wine pairing!": "ფრანგული სტილის რეცეპტები + მომზადების ინსტრუქცია + ღვინის შეხამება!",
    "Safe, personalized workouts without generic advice!": "უსაფრთხო, პერსონალიზებული ვარჯიშები ზოგადი რჩევების გარეშე!",
    "Add personality:": "დაამატეთ პერსონაჟის ხასიათი:",
    "Include examples in instructions:": "ჩართეთ მაგალითები ინსტრუქციებში:",
    "Leverage Google Drive:": "გამოიყენეთ Google Drive:",
    "Share with teams:": "გაუზიარეთ გუნდებს:",
    "Test before sharing:": "გატესტეთ გაზიარებამდე:",
    "Use conversation starters:": "გამოიყენეთ საუბრის დამწყები ფრაზები (Conversation starters):",
    "Don't be too vague:": "არ იყოთ ზედმეტად ბუნდოვანი:",
    "Don't overcomplicate:": "არ გაართულოთ ზედმეტად:",
    "Don't ignore tone:": "არ უგულებელყოთ ტონი:",
    "Don't forget constraints:": "არ დაგავიწყდეთ შეზღუდვები:",
    "Don't share sensitive data:": "არ გააზიაროთ სენსიტიური მონაცემები:",
    "Don't create redundant Gems:": "არ შექმნათ ერთმანეთის მსგავსი, ზედმეტი Gem-ები:",
    "Iterate and Improve:": "გააუმჯობესეთ ციკლურად:",
    "Create initial Gem → Test with real prompts": "შექმენით თავდაპირველი Gem → გატესტეთ რეალური პრომპტებით",
    "Identify gaps in responses → Update instructions": "იპოვეთ ხარვეზები პასუხებში → განაახლეთ ინსტრუქციები",
    "Add reference files as you discover needs": "დაამატეთ საყრდენი ფაილები საჭიროების მიხედვით",
    "Share updated version → Team benefits immediately": "გააზიარეთ განახლებული ვერსია → გუნდი მყისიერად მიიღებს სარგებელს",
    "Power User Tip: Gem Collections": "ძლიერი მომხმარებლის რჩევა: Gem-ების კოლექციები",
    "Create \"Gem Families\" for complex workflows:": "შექმენით \"Gem-ების ოჯახები\" რთული სამუშაო პროცესებისთვის:",
    "Choose Gems if:": "აირჩიეთ Gems თუ:",
    "Choose GPTs if:": "აირჩიეთ GPTs თუ:",
    "Choose Claude Projects if:": "აირჩიეთ Claude Projects თუ:",
    "Use all three?": "გამოვიყენოთ სამივე?",
    "Many professionals use different tools for different tasks - that's OK!": "ბევრი პროფესიონალი იყენებს სხვადასხვა ინსტრუმენტს სხვადასხვა ამოცანისთვის - და ეს ნორმალურია!",
    "Brainstorming framework (SCAMPER, 6 Thinking Hats?)": "იდეების გენერაციის ჩარჩო (SCAMPER, 6 კოგნიტური ქუდი)",
    "Start simple → iterate → improve continuously": "დაიწყეთ მარტივად → განაახლეთ → გააუმჯობესეთ მუდმივად",
    "Agents ≠ Custom GPTs → ავტონომიური multi-step execution": "Agents ≠ Custom GPTs → ავტონომიური მრავალეტაპიანი შესრულება",
    "Higher costs & risks → use for complex workflows only": "უფრო მაღალი ხარჯები და რისკები → გამოიყენეთ მხოლოდ რთული პროცესებისთვის",
    "Upload relevant documents → GPT becomes domain expert": "ატვირთეთ რელევანტური დოკუმენტები → GPT ხდება სფეროს ექსპერტი",
    "Quality > Quantity - curate useful files": "ხარისხი > რაოდენობაზე - შეარჩიეთ მხოლოდ სასარგებლო ფაილები",
    "Update regularly as information changes": "განაახლეთ რეგულარულად, როცა ინფორმაცია იცვლება",
    "Anonymize sensitive data before upload!": "ატვირთვამდე წაშალეთ იდენტიფიცირებადი (სენსიტიური) მონაცემები!",
    "Private GPTs for sensitive information": "პირადი (Private) GPTs სენსიტიური ინფორმაციისთვის",
    "Never upload confidential data, PII, passwords": "არასოდეს ატვირთოთ კონფიდენციალური მონაცემები ან პაროლები",
    "Public GPTs → anyone sees instructions & files": "საჯარო GPTs → ყველას შეუძლია ნახოს ინსტრუქციები და ფაილები",
    "Use Enterprise accounts for company data": "გამოიყენეთ Enterprise ანგარიშები კომპანიის მონაცემებისთვის",
    "Georgian Context Matters": "ქართულ კონტექსტს დიდი მნიშვნელობა აქვს",
    "Customize for Georgian audience (language, culture, formality)": "მოარგეთ ქართულ აუდიტორიას (ენა, კულტურა, ფორმალობა)",
    "Include Georgian business conventions": "გაითვალისწინეთ ქართული ბიზნეს კონვენციები",
    "This Week:": "ამ კვირაში:",
    "Next Month:": "მომავალ თვეში:",
    "Adversarial Attacks:სპეციალურად შექმნილი input-ები": "Adversarial Attacks: სპეციალურად მანიპულირებული შეყვანილი მონაცემები (Input)",
    "Unauthorized Access:API Keys-ის მოპარვა/გამჟღავნება": "არასანქცირებული წვდომა: API Keys-ის მოპარვა/გამჟღავნება",
    "Hardcoding in Code:API key პირდაპირ წყაროს კოდში": "Hardcoding: API გასაღების პირდაპირ კოდში ჩაწერა",
    "Client-Side Exposure:API გასაღები JavaScript კოდში": "კლიენტის მხარეს გამჟღავნება: API გასაღები ღიად JavaScript-ში",
    "No Rotation:API key-ს როტაცია არ ხდება": "როტაციის ნაკლებობა: API გასაღების რეგულარულად არ განახლება",
    "Test on Diverse Groups": "გატესტეთ სხვადასხვა დემოგრაფიულ ჯგუფზე",
    "Analyze Language Patterns": "გაანალიზეთ ენობრივი შაბლონები და მიკერძოება",
    "Compare \"male/female\" prompts": "შეადარეთ გენდერული პრომპტების მოდელები",
    "Feedback AI platforms-ს": "მიაწოდეთ უკუკავშირი AI პლატფორმებს",
    "Fines:Up to €35M or 7% of global revenue!": "ჯარიმები: 35 მილიონ ევრომდე ან გლობალური შემოსავლის 7%!",
    "Timeline:2026-2027 phased implementation": "ვადები: 2026-2027 წლების ეტაპობრივი დანერგვა",
    "Extraterritorial:Applies to non-EU companies if AI used in EU": "ექსტრატერიტორიული: ეხება არა-EU კომპანიებსაც, თუ AI გამოიყენება ევროპაში",
    "Best Practice:მიჰყევით EU AI Act-ს international clients-თან მუშაობისას": "საუკეთესო პრაქტიკა: მიჰყევით EU AI Act-ს საერთაშორისო კლიენტებთან მუშაობისას",
    "Human Oversight:AI = recommendation, HR = decision": "ადამიანური ზედამხედველობა: AI = რეკომენდაციას, ადამიანი = გადაწყვეტილებას",
    "Data Leakage, GDPR/NDA breach, Client trust დარღვევა": "მონაცემთა გაჟონვა, GDPR/NDA-ს დარღვევა, კლიენტის ნდობის დაკარგვა",
    "Data Anonymization, Enterprise AI (ChatGPT Team), ან Local AI (Ollama)": "მონაცემთა ანონიმიზაცია, კომპორატიული (Enterprise) AI ან ლოკალური მოდელები",
    "Allowed tools list": "ნებადართული ხელსაწყოების სია",
    "Conditional tools (requires approval)": "პირობითი ხელსაწყოები (მოითხოვს დასტურს)",
    "Internal:মხოლოდ enterprise AI": "შიდა გამოყენება: მხოლოდ კორპორატიული AI",
    "Research & ideation": "კვლევა და იდეების გენერაცია",
    "Human review required": "აუცილებელია ადამიანის მიერ გადამოწმება",
    "Human review mandatory": "ადამიანის ავტორიზაცია სავალდებულოა",
    "Accuracy verification": "სიზუსტის შემოწმება და ვალიდაცია",
    "Up to €20M or 4% of global annual turnover!": "20 მილიონ ევრომდე ან გლობალური წლიური ბრუნვის 4%!",
    "Data Anonymization:წაშალეთ PII (Personally Identifiable Information)": "მონაცემთა ანონიმიზაცია: წაშალეთ პერსონალურად იდენტიფიცირებადი ინფორმაცია (PII)"
}

for eng, geo in replacements.items():
    # Replace simple strings using case-insensitive if needed, but exact is fine here
    # Use re to replace flexibly around spaces or colons if needed, but simple replace works 99% of time
    text = text.replace(eng, geo)

# Some specific edge cases
text = text.replace("Max:20 files, 512MB each", "მაქსიმუმ: 20 ფაილი, თითო 512MB")
text = text.replace("Web Browsing - თუ გჭირდებათ current info", "Web Browsing - თუ გჭირდებათ უახლესი ინფორმაცია")
text = text.replace("Code Interpreter - თუ არ გჭირდებათ data analysis", "Code Interpreter - თუ გჭირდებათ მონაცემთა ანალიზი")
text = text.replace("Anyone with link:share link-ით", "Anyone with link: გაზიარებული ბმულით")
text = text.replace("Result:Full-length SEO blog posts in minutes instead of hours!", "შედეგი: სრულყოფილი SEO ბლოგები წუთებში!")


with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print("Translation replacements completed.")
